"""Add cascade delete to OrderProduct foreign key

Revision ID: 5755f0180858
Revises: f9a76d756251
Create Date: 2024-08-22 17:23:34.788848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5755f0180858'
down_revision: Union[str, None] = 'f9a76d756251'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('order_products_order_id_fkey', 'order_products', type_='foreignkey')
    op.drop_constraint('order_products_product_id_fkey', 'order_products', type_='foreignkey')
    op.create_foreign_key(None, 'order_products', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'order_products', 'orders', ['order_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order_products', type_='foreignkey')
    op.drop_constraint(None, 'order_products', type_='foreignkey')
    op.create_foreign_key('order_products_product_id_fkey', 'order_products', 'products', ['product_id'], ['id'])
    op.create_foreign_key('order_products_order_id_fkey', 'order_products', 'orders', ['order_id'], ['id'])
    # ### end Alembic commands ###
